name: Build the pages
on: push

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/checkout@v4
        name: Checkout simplog
        with:
          repository: 'cueavy/simplog'
          path: 'simplog'
      - uses: actions/setup-python@v5
        name: Setup python
      - name: Build
        run: |
          python -m pip install -r requirements.txt
          python simplog/blog.py -build
      - uses: actions/configure-pages@v5
        name: Setup Pages
      - uses: actions/upload-pages-artifact@v3
        name: Upload artifact
        with:
          path: 'output'
      - uses: actions/deploy-pages@v4
        name: Deploy to GitHub Pages
        id: deployment
